const SET_TOAST_SUCCESS = 'SET_TOAST_SUCCESS';
const SET_TOAST_ERROR = 'SET_TOAST_ERROR';
const SET_TOAST_INFO = 'SET_TOAST_INFO';
const SET_TOAST_WARNING = 'SET_TOAST_WARNING';
const CLEAR_TOAST = 'CLEAR_TOAST';

const toasts_action_types = {
    SET_TOAST_SUCCESS: SET_TOAST_SUCCESS,
    SET_TOAST_ERROR: SET_TOAST_ERROR,
    SET_TOAST_INFO: SET_TOAST_INFO,
    SET_TOAST_WARNING: SET_TOAST_WARNING,
    CLEAR_TOAST: CLEAR_TOAST,
};

export default toasts_action_types;